### ISSUE TITLE
Cannot install - 500 Internal Server Error

### ISSUE THREAD

**Issue by endystrike** [mitydigital/statamic-feedamic#12]
### Bug description

Only when I try to install Feedamic, it says "Status: 500 Internal Error" and installation doesn't complete

### Steps to reproduce

Just trying to install Feedamic from my statamic control panel.
[https://i.imgur.com/HUKZrgu.png](url)

### Environment and versions

```yaml
Siteground VPS hosting (10 cores, 14 gb ram)
PHP Version 8.1.17
```

**Comment by martyf** [comment]
You'll need to check your error logs for details. 

It is recommended to install any add-on via the command line rather than the CP.
