### ISSUE TITLE
Idea: Ability to specify a query scope for feed query

### ISSUE THREAD

**Issue by jacksleight** [mitydigital/statamic-feedamic#20]
I'm working on a site where only certain entries from the collection should be included in the feed (it has some entries that are published but aren't real articles). It'd be great if there was a way to filter these out.

I thought the simplest and most flexible approach would be the ability to specify a query scope in the feed config, that way you can apply any conditions you like.

**Comment by martyf** [comment]
Great idea... I've got this working but just need to head out so will push a little later. Stay tuned.

**Comment by martyf** [comment]
Can I please get you to give this a whirl:
https://github.com/mitydigital/statamic-feedamic/tree/feature/support-query-scopes

Add a `scope` param to your config, referencing the Query Scope you've built for your app. 

Feedamic should then pick it up and apply it to the existing Feedamic logic.

**Comment by jacksleight** [comment]
This works great! My only suggestion would be passing the feed config (or at least the name) to the scope parameters, that way you could use a single scope class to set different conditions depending on the feed it's being applied to.

**Comment by martyf** [comment]
This has been released in 2.3.0 - thanks for the suggestion Jack!

See the docs for how to use the new `scope` and `view` config options:
https://docs.mity.com.au/feedamic/configuration/feeds
