### ISSUE TITLE
Carbon Error since upgrading to Statamic v5

### ISSUE THREAD

**Issue by atomicjam** [mitydigital/statamic-feedamic#24]
### Bug description

Been using feedamic for a while successfully upgraded to statamic v5, statamic and other plugins are working but feedamic throws carbon error on /feed. 

Object of class Illuminate\Support\Carbon could not be converted to int

### Steps to reproduce

run statamic v5 and visit /feed

### Environment and versions

```yaml
Environment
Application Name: Laravel
Laravel Version: 10.48.10
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.0.2 PRO

Statamic Addons
mitydigital/feedamic: 2.3.2
mitydigital/sitemapamic: 3.0.1
rias/statamic-redirect: 3.7.1
```

### Additional details

ive cleared all the caches and used the php please feedamic:clear

attached are log files 

[2024-05-14 08:53:09] local.ERROR: Object of class Illuminate\Support\Carbon could not be converted to int {"exception":"[object] (ErrorException(code: 0): Object of class Illuminate\\Support\\Carbon could not be converted to int at /var/www/html/vendor/statamic/cms/src/Query/Builder.php:650)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/vendor/statamic/cms/src/Query/Builder.php(650): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/statamic/cms/src/Stache/Query/Builder.php(153): Statamic\\Query\\Builder->filterTestLessThanOrEqualTo()
#3 [internal function]: Statamic\\Stache\\Query\\Builder->Statamic\\Stache\\Query\\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(911): array_filter()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(387): Illuminate\\Support\\Arr::where()
#6 /var/www/html/vendor/statamic/cms/src/Stache/Query/Builder.php(150): Illuminate\\Support\\Collection->filter()
#7 /var/www/html/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(101): Statamic\\Stache\\Query\\Builder->filterWhereBasic()
#8 /var/www/html/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(87): Statamic\\Stache\\Query\\EntryQueryBuilder->getKeysFromCollectionsWithWhere()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(791): Statamic\\Stache\\Query\\EntryQueryBuilder->Statamic\\Stache\\Query\\{closure}()
#10 /var/www/html/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(84): Illuminate\\Support\\Collection->reduce()
#11 /var/www/html/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(86): Statamic\\Stache\\Query\\EntryQueryBuilder->getKeysFromCollectionsWithWheres()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(791): Statamic\\Stache\\Query\\EntryQueryBuilder->Statamic\\Stache\\Query\\{closure}()
#13 /var/www/html/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(84): Illuminate\\Support\\Collection->reduce()
#14 /var/www/html/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(68): Statamic\\Stache\\Query\\EntryQueryBuilder->getKeysFromCollectionsWithWheres()
#15 /var/www/html/vendor/statamic/cms/src/Stache/Query/Builder.php(26): Statamic\\Stache\\Query\\EntryQueryBuilder->getFilteredKeys()
#16 /var/www/html/vendor/statamic/cms/src/Stache/Query/Builder.php(45): Statamic\\Stache\\Query\\Builder->resolveKeys()
#17 /var/www/html/vendor/statamic/cms/src/Query/Concerns/FakesQueries.php(18): Statamic\\Stache\\Query\\Builder->Statamic\\Stache\\Query\\{closure}()
#18 /var/www/html/vendor/statamic/cms/src/Stache/Query/Builder.php(44): Statamic\\Query\\Builder->withFakeQueryLogging()
#19 /var/www/html/vendor/statamic/cms/src/Query/Builder.php(584): Statamic\\Stache\\Query\\Builder->Statamic\\Stache\\Query\\{closure}()
#20 /var/www/html/vendor/statamic/cms/src/Stache/Query/Builder.php(44): Statamic\\Query\\Builder->onceWithColumns()
#21 /var/www/html/vendor/mitydigital/feedamic/src/Http/Controllers/FeedamicController.php(201): Statamic\\Stache\\Query\\Builder->get()
#22 [internal function]: MityDigital\\Feedamic\\Http\\Controllers\\FeedamicController->MityDigital\\Feedamic\\Http\\Controllers\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(600): array_map()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\\Support\\Arr::map()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(404): Illuminate\\Support\\Collection->map()
#26 /var/www/html/vendor/mitydigital/feedamic/src/Http/Controllers/FeedamicController.php(138): Illuminate\\Support\\Collection->flatMap()
#27 /var/www/html/vendor/mitydigital/feedamic/src/Http/Controllers/FeedamicController.php(54): MityDigital\\Feedamic\\Http\\Controllers\\FeedamicController->loadFeedEntries()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(437): MityDigital\\Feedamic\\Http\\Controllers\\FeedamicController->MityDigital\\Feedamic\\Http\\Controllers\\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(429): Illuminate\\Cache\\Repository->rememberForever()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\\Cache\\CacheManager->__call()
#31 /var/www/html/vendor/mitydigital/feedamic/src/Http/Controllers/FeedamicController.php(54): Illuminate\\Support\\Facades\\Facade::__callStatic()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(437): MityDigital\\Feedamic\\Http\\Controllers\\FeedamicController->MityDigital\\Feedamic\\Http\\Controllers\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(429): Illuminate\\Cache\\Repository->rememberForever()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\\Cache\\CacheManager->__call()
#35 /var/www/html/vendor/mitydigital/feedamic/src/Http/Controllers/FeedamicController.php(52): Illuminate\\Support\\Facades\\Facade::__callStatic()
#36 /var/www/html/vendor/mitydigital/feedamic/src/Http/Controllers/FeedamicController.php(29): MityDigital\\Feedamic\\Http\\Controllers\\FeedamicController->getXml()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): MityDigital\\Feedamic\\Http\\Controllers\\FeedamicController->rss()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#43 /var/www/html/vendor/spatie/laravel-csp/src/AddCspHeaders.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Spatie\\Csp\\AddCspHeaders->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#58 /var/www/html/vendor/rias/statamic-redirect/src/Http/Middleware/HandleNotFound.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Rias\\StatamicRedirect\\Http\\Middleware\\HandleNotFound->handle()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#67 /var/www/html/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle()
#69 /var/www/html/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle()
#71 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#73 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#75 /var/www/html/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#77 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#79 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#80 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#82 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#83 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#84 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#85 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#86 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#87 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#88 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#89 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#90 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#91 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#92 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#93 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#94 /var/www/html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#95 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(16): require_once('...')
#96 {main}
"}

**Comment by martyf** [comment]
Can you please make a repo of the issue, or provide more step-by-step instructions as to how to replicate it from a clean install?

I'm not able to replicate the issue.

**Comment by atomicjam** [comment]
Hey Marty, thanks I've updated the other issue with details of the repo save doing it in both places as I think you are right it's probably a similar issue.

**Comment by martyf** [comment]
This is This has been resolved in 2.3.3. A `composer update` should take care of it.

**Comment by atomicjam** [comment]
amazing thanks again

**Comment by martyf** [comment]
No worries 🎉
