### ISSUE TITLE
Feature: Separate feeds for multiple collections

### ISSUE THREAD

**Issue by jacksleight** [mitydigital/statamic-feedamic#7]
I'm working on a site at the moment that has two separate blogs each with their own collection, and I need to create separate feeds for each. It'd be amazing if Feedamic could support this.

I'd be very happy to PR this if it's something you might consider adding, only thing is I'm not sure how the config would work as the current structure is only really set up for a single feed.

**Comment by martyf** [comment]
Hey Jack, this is a really good idea, but as you said, config is the trouble part.

I think it should be straight forward to implement - assuming a decent config structure is defined.

I'd love to have a realtime chat about this sometime if you're open to it? I think it is a great idea, but one that may be good to bounce back and forth to find the best way to keep config simple for newcomers, but also flexible for more power users too. Let me know if you're happy to have a chat sometime.

**Comment by jacksleight** [comment]
> I'd love to have a realtime chat about this sometime if you're open to it?

Sure thing sounds good! DM me on Twitter or Discord and we can fix up a time. 👍

**Comment by martyf** [comment]
Forgot to close this one... implemented with 2.2 - thanks Jack!
