### ISSUE TITLE
Dates not reporting correctly on some readers

### ISSUE THREAD

**Issue by spaceageliving** [mitydigital/statamic-feedamic#9]
### Bug description

On some readers (like NetNewsWire on iPad, see photo), dates are not being reported correctly--dates are showing Dec 31, 1969 for all entries. Other readers, like Reedy on MacOS, not a problem.

NetNewsReader:

![IMG_0232](https://user-images.githubusercontent.com/874600/193426637-af643f01-32f5-483c-815a-d908ac0c89f3.jpeg)

Reedy:

<img width="1322" alt="Screen Shot 2022-10-01 at 2 14 12 PM" src="https://user-images.githubusercontent.com/874600/193426759-cf2d8ad3-35fb-4e42-9781-66b05ccf5c01.png">

### Steps to reproduce

Open feed in NetNewsWire, Reeder.

### Environment and versions

```yaml
Statamic 3.3.36 Pro
Laravel 8.83.23
PHP 8.1.8
aerni/social-links 2.3.1
mitydigital/feedamic 2.2.0
optimoapps/statamic-bard-text-align 1.0.2
stillat/meerkat 2.6.0
```

**Comment by spaceageliving** [comment]
Update: I published the views, and updated the date outputs to use ->toRfc2822String(), which formats the year as 4 digits as opposed to 2 digits when using ->toRfc822String(). This seems to fix the problem, continuing to test.

**Comment by martyf** [comment]
Thanks for creating this issue.

Can you confirm that you're only seeing the issue with the RSS feed, but not with the Atom feed?

**Comment by spaceageliving** [comment]
Atom feed seems fine without modification on NetNewsReader (iPadOS) and Reeder (MacOS).

Everything looks good for RSS feed using ->toRfc2822String().

**Comment by martyf** [comment]
Cool bananas - I've release 2.2.1 which addresses this issue. 

Thanks for your help with this, and the quality of your issue report: really appreciate it!

**Comment by spaceageliving** [comment]
Thanks for making this package! Big help...

**Comment by martyf** [comment]
Woot! Really glad you've found it useful 😁
